In [2]:
import numpy as np


In [6]:
# create array , matrix
a=np.array([1,2,3,4])

In [4]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [7]:
#shape
print(a.shape,b.shape)

(4,) (2, 2)


In [8]:
#reshape
c=a.reshape(4,1)
c.shape

(4, 1)

In [15]:
d=b.reshape(2,2,1)
d.shape


(2, 2, 1)

In [5]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [16]:
a=np.array([1,2,3])
b=np.array([3,4])
c=np.concatenate((a,b))
c

array([1, 2, 3, 3, 4])

In [18]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
c

array([5, 7, 9])

In [19]:
c=np.array([10])
d=a+c
d

array([11, 12, 13])

In [20]:
e=a+5
e

array([6, 7, 8])

In [6]:
a=np.array([1,2,3,4,5,6,7,8])
a.shape

(8,)

In [24]:
b=a[2:7:2]
b

array([3, 5, 7])

In [3]:
c=a[a>3]
c

NameError: name 'a' is not defined

In [27]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
sum_a=np.sum(a)
sum_a

np.int64(36)

In [32]:
max_a=np.max(a)

In [33]:
max_a

np.int64(8)

In [8]:
min_a=np.min(a)
min_a

np.int64(1)

In [9]:
a=np.array([1,4,3,6,7,9,2,5,8])
b=np.sort(a)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#matris random
a=np.random.randint(0,10,(3,4))
a

array([[8, 6, 1, 1],
       [0, 8, 3, 8],
       [2, 9, 5, 8]], dtype=int32)

In [7]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.stack((a,b))
d=np.hstack((a,b))
c


array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#normalize
a

array([1, 2, 3])

In [9]:
min_a=np.mean(a)
min_a

np.float64(2.0)

In [10]:
std_a=np.std(a)
std_a

np.float64(0.816496580927726)

In [11]:
norm_a=(a-min_a)/std_a
norm_a

array([-1.22474487,  0.        ,  1.22474487])

In [12]:
np.mean(norm_a)

np.float64(0.0)

In [13]:
np.std(norm_a)

np.float64(0.9999999999999999)